ProjectTwo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('catalog.urls')),
    path('',include('system.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path,include
from rest_framework import routers
from .views import (
    home,
    BookListView,
    BookDetailView,
    AuthorListView,
    AuthorDetailView,
    LoanedBooksByUserListView,
    LoanedBooksListView,
    renew_book_librarian,
    AuthorCreateView,
    AuthorUpdate,
    AuthorDelete,
    BookCreateView,
    BookUpdate,
    BookDelete,
    BlogDetailView,
    about,
    dashboard,
    profile,
    # form,
    BlogCreateView,
    BookInstanceCreateView,
    signUpView,
    
    
)
urlpatterns = [
    path('author/create/', AuthorCreateView.as_view(), name='author-create'),
    path('user/register/', signUpView, name='register'),
    path('book/create/', BookCreateView.as_view(), name='book-create'),
    path('blog/create/', BlogCreateView.as_view(), name='blog-create'),
    path('',home,name="catalog"),
    path('dashboard/',dashboard,name="dashboard"),
    path('profile/',profile,name="profile"),
    path('book/loan/', BookInstanceCreateView, name='loan-book'),
    path('about/',about,name="about"),
    # path('form/',form,name="form"),
    path('blog/<slug:slug>/',BlogDetailView.as_view(),name="blog"),
    path('book/list/',BookListView.as_view(),name="books"),
    path('mybooks/',LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<slug:slug>/',BookDetailView.as_view(),name="book"),
    path('author/list/',AuthorListView.as_view(),name="authors"),
    path('books/borrowed/',LoanedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', renew_book_librarian, name='renew-book-librarian'),
    path('book/<slug:slug>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<slug:slug>/delete/',BookDelete.as_view(), name='book-delete'),
    path('author/<slug:slug>/',AuthorDetailView.as_view(),name="author"),
    path('author/<slug:slug>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('author/<slug:slug>/delete/',AuthorDelete.as_view(), name='author-delete'),
]

system/urls.py
from django.urls import path
from .views import (
    home,
    page,
    index,
    CreateView,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',home,name="home"),
    path('index/',index,name="index"),
    path('page/',page,name="page"),
    path('create-course/',CreateView.as_view(),name="create-course"),
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid 
from django.utils.text import slugify
from django.urls import reverse
from datetime import date, datetime

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=50)
    date_birth = models.DateField(blank=True, null=True)
    date_death = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='images/authors/',blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("author", kwargs={"slug": self.slug})
    def save(self, *args, **kwargs):
       if not self.slug:
        self.slug = slugify(self.name)
       super(Author, self).save(*args, **kwargs) # Call the real save() method   

class Book(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)
    author = models.ForeignKey(Author, related_name='writter', on_delete=models.SET_NULL,null=True)
    summary = models.TextField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True,default=25.5)
    isbn = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/books/',blank=True, null=True)
    genre = models.ManyToManyField(Genre,related_name="my_book")
    language = models.ForeignKey(Language, on_delete=models.SET_NULL,null=True)
    def save(self, *args, **kwargs):
       if not self.slug:
        self.slug = slugify(self.title)
       super(Book, self).save(*args, **kwargs) # Call the real save() method
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("book", kwargs={"slug": self.slug})
        
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ' '.join(genre.name for genre in self.genre.all()[:3])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    due_back = models.DateField()
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    user = models.ForeignKey(User, related_name='borrower', on_delete=models.SET_NULL, null=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)
    def save(self, *args, **kwargs):
        if self.status == 'm' or self.status == 'a':
            self.status = 'o'
        super(BookInstance, self).save(*args, **kwargs) # Call the real save() method
    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)

class SingleBlog(models.Model):
    title = models.CharField(max_length=50,blank=True, null=True,default=" ")
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/blogs/%d-%m-%y/',blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.title or "no-title"


class Blog(models.Model):
    title = models.CharField(max_length=50,blank=True, null=True,default=" ")
    image = models.ImageField(upload_to='images/blogs/%d-%m-%y/',blank=True, null=True)
    blogs = models.ManyToManyField('SingleBlog')
    slug = models.SlugField(blank=True, null=True)
    date = models.DateField(auto_now_add=True,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    def save(self, *args, **kwargs):
       if not self.slug:
        self.slug = slugify(self.title)
       super(Blog, self).save(*args, **kwargs) # Call the real save() method
    def get_absolute_url(self):
        return reverse("blog", kwargs={"slug": self.slug})
    def __str__(self):
        return self.title or "no title"
    
class Message(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254,blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True,blank=True, null=True)
    def __str__(self):
        return self.name
    def has_been(self):
        if self.date:
            return (datetime.now() - self.date)

class Adress(models.Model):
    street = models.CharField(max_length=50,blank=True, null=True)
    city = models.CharField(max_length=50,blank=True, null=True)
    state = models.CharField(max_length=50,blank=True, null=True)
    def __str__(self):
        return self.state

class Skill(models.Model):
    name = models.CharField(max_length=50,blank=True, null=True)
    power = models.IntegerField(blank=True, null=True,default=50)
    def __str__(self):
        return self.name
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True, null=True)
    email = models.EmailField(max_length=254,blank=True, null=True)
    image = models.ImageField(upload_to="images/users/",default="images/user.png")
    website = models.URLField(max_length=200,blank=True, null=True)
    adresse = models.ForeignKey(Adress, on_delete=models.CASCADE,blank=True, null=True)
    name = models.CharField(max_length=50,blank=True, null=True)
    nikname = models.CharField(max_length=50,blank=True, null=True)
    skills = models.ManyToManyField(Skill)
    def __str__(self):
        return str(self.name)
    
class Activity(models.Model):
    name = models.CharField(max_length=50,blank=True, null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return self.user.username

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime
from .models import Author,Book,BookInstance,Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ("name","email","nikname","image","website","skills")
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).",widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
            raise ValidationError(_("the new date in the future not in the past you idiot!"))
        if data > (datetime.date.today() + datetime.timedelta(weeks=4)):
            raise ValidationError(_("you will borrow the book not owned ! pick it for a short time"))
        return data

class AuthorForm(forms.ModelForm):
    
    class Meta:
        model = Author
        fields = ['name', 'date_birth', 'date_death']
        widgets = {
            'date_birth': forms.DateInput(attrs={'type': 'date'}),
            'date_death': forms.DateInput(attrs={'type': 'date'})
        }
    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            # if visible.field.widget.input_type == 'text':
            #     print(visible.field)
            visible.field.widget.attrs['class'] = 'form-control form-control-rounded'

class BookForm(forms.ModelForm):
    
    class Meta:
        model = Book
        fields = ['title','author','summary','image','language','genre','isbn']
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class BookInstanceForm(forms.ModelForm):
    
    class Meta:
        model = BookInstance
        fields = ("book","due_back","imprint","status")
        widgets = {
            'due_back': forms.DateInput(attrs={'type': 'date'}),
        }
    def __init__(self, *args, **kwargs):
        super(BookInstanceForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
   
    def clean_due_back(self):
        due_back = self.cleaned_data.get('due_back')
        if due_back < datetime.date.today():
            raise ValidationError("Please Enter A valid Date ")
        return due_back 

catalog/templates/catalog/author.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    {% if author %}    
    <h1>Author: {{author.name}}</h1>
    <p>{{author.date_birth}}</p>
    {% if author.writter.all %}
        <h2>Books</h2>
        <ul>
            {% for book in  author.writter.all%}
                <li>
                    <a href="{{book.get_absolute_url}}"><span class="text-primary">{{book.title}} #{{ forloop.counter }}</span></a>
                    <p>{{book.summary}}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
    dont work
    {% endif %}
    {% if request.user.is_staff %}    
    <div class="admin">
      <a href="{% url 'author-update' author.slug %}"><img src="{% static 'images/update.png' %}" style="width:50px;height:50px;margin-right:15px;" alt=""></a>
      <a href="{% url 'author-delete' author.slug %}"><img src="{% static 'images/delete.png' %}" style="width:50px;height:50px" alt=""></a>
    </div>
    {% endif %}
    {% endif %}
{% endblock content %}

catalog/templates/catalog/authors.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }}</a><span>({{author.date_birth}}-{{author.date_death}})</span>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Author in our day.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
<div class="container" style="padding:15px 5px 10px 0;">
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author' book.author.slug %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  {% comment %} <p><strong>ISBN:</strong> {{ book.isbn }}</p> {% endcomment %}
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
    <img src="{{book.image.url}}" style="widht:250px;height:250px;" alt="{{book.title}}">
    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    {% endfor %}

    {% if request.user.is_staff %}    
    <div class="admin">
      <a href="{% url 'book-update' book.slug %}"><img src="{% static 'images/update.png' %}" style="width:50px;height:50px;margin-right:15px;" alt=""></a>
      <a href="{% url 'book-delete' book.slug %}"><img src="{% static 'images/delete.png' %}" style="width:50px;height:50px" alt=""></a>
    </div>
    {% endif %}
    
  </div>
</div>
{% endblock %}

catalog/templates/catalog/book_instance_list.html
{% extends "base_generic.html" %}

{% block content %}
      
    <h1>All Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book' bookinst.book.slug %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}){% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}

{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book' bookinst.book.slug %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/delete_author.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/delete_book.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the Book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/new_author.html
  <form action="{% url 'author-create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

catalog/templates/catalog/new_book.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/update_author.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/update_book.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}